from N2G import drawio_diagram
from datetime import datetime
import time

current_time=datetime.now()
nowtime=current_time.strftime("%Y-%m-%d %H:%M:%S")

# Define style nha bro
router='./styles/router.txt'
coresw='./styles/coresw.txt'
asw='./styles/asw.txt'
wlc='./styles/wlc.txt'

# Define link nha bro
link_style='./links/gapkhuc.txt'

diagram = drawio_diagram()
diagram.add_diagram("Page-1")

# add note nha bro
diagram.add_node(id="SSC-Core", style=coresw)
diagram.add_node(id="B2S-BgC-RTR-001", style=router)
diagram.add_node(id="SSC-M-SW4", style=asw)
diagram.add_node(id="SSC-WLC-5508", style=wlc)
diagram.add_node(id="SSC-WLC-5508", style=wlc)
diagram.add_node(id="SSC-M-SW3", style=asw)
diagram.add_node(id="SSC-M-SW3", style=asw)
diagram.add_node(id="SSC-R2", style=router)
diagram.add_node(id="SSC-R1", style=router)
diagram.add_node(id="SSC-M-SW01", style=asw)
diagram.add_node(id="SSC-M-SW01", style=asw)
diagram.add_node(id="SSC-M-SW02", style=asw)
diagram.add_node(id="SSC-M-SW02", style=asw)
diagram.add_node(id="PDC-N9K5-01", style=coresw)
diagram.add_node(id="CTY-CSW-001", style=coresw)
diagram.add_node(id="CTY-CSW-001", style=coresw)
diagram.add_node(id="SSC-Server-SW", style=asw)
diagram.add_node(id="SSC-Server-SW", style=asw)
diagram.add_node(id="SDC-N9K5-01", style=coresw)
diagram.add_node(id="SSC-FL4-SW12", style=asw)
diagram.add_node(id="SSC-FL4-SW11", style=asw)
diagram.add_node(id="SSC-FL4-SW10", style=asw)
diagram.add_node(id="SSC-FL3-SW1", style=asw)
diagram.add_node(id="SSC-FL4-SW6", style=asw)
diagram.add_node(id="SSC-FL4-SW6", style=asw)
diagram.add_node(id="SSC-FL4-SW7", style=asw)
diagram.add_node(id="SSC-FL4-SW7", style=asw)
diagram.add_node(id="SSC-nternet-SW1", style=asw)
diagram.add_node(id="SSC-FL2-SW2", style=asw)
diagram.add_node(id="SSC-FL2-SW2", style=asw)
diagram.add_node(id="SSC-nternet-SW1", style=asw)
diagram.add_node(id="SSC-FL4-SW4", style=asw)
diagram.add_node(id="SSC-FL4-SW4", style=asw)
diagram.add_node(id="SSC-FL2-SW3", style=asw)
diagram.add_node(id="SSC-FL2-SW3", style=asw)
diagram.add_node(id="SSC-FL3-SW2", style=asw)
diagram.add_node(id="SSC-FL4-SW5", style=asw)
diagram.add_node(id="HO-FL4-SW", style=asw)
diagram.add_node(id="SSC-FL2-SW4", style=asw)
diagram.add_node(id="SSC-FL2-SW4", style=asw)
diagram.add_node(id="SSC-FL3-SW5", style=asw)
diagram.add_node(id="SSC-FL4-SW2", style=asw)
diagram.add_node(id="SSC-FL4-SW2", style=asw)
diagram.add_node(id="SSC-FL2-SW5", style=asw)
diagram.add_node(id="SSC-FL2-SW5", style=asw)
diagram.add_node(id="SSC-FL5-SW2", style=asw)
diagram.add_node(id="SSC-FL5-SW2", style=asw)
diagram.add_node(id="SSC-FL3-SW4", style=asw)
diagram.add_node(id="SSC-FL4-SW3", style=asw)
diagram.add_node(id="SSC-FL5-SW1", style=asw)
diagram.add_node(id="SSC-FL5-SW1", style=asw)
diagram.add_node(id="SSC-FL3-SW7", style=asw)
diagram.add_node(id="SSC-FL4-SW1", style=asw)
diagram.add_node(id="SSC-FL4-SW1", style=asw)
diagram.add_node(id="SSC-FL2-SW8", style=asw)
diagram.add_node(id="SSC-FL2-SW8", style=asw)
diagram.add_node(id="SSC-FL4-SW8", style=asw)
diagram.add_node(id="SSC-FL4-SW8", style=asw)
diagram.add_node(id="HO-SW3560X", style=coresw)

# Add link nha Bro
diagram.add_link("SSC-Core","B2S-BgC-RTR-001", label="Gg 1/3/26 to Gig 0/0/0",style=link_style)
diagram.add_link("SSC-Core","SSC-M-SW4",label="Gg 1/4/1  to Gig 1/0/28",style=link_style)
diagram.add_link("SSC-Core","SSC-WLC-5508",label="Gg 1/3/36 to Gig 0/0/1",style=link_style)
diagram.add_link("SSC-Core","SSC-WLC-5508",label="Gg 2/3/36 to Gig 0/0/2",style=link_style)
diagram.add_link("SSC-Core","SSC-M-SW3",label="Gg 2/2/3  to Gig 1/0/51",style=link_style)
diagram.add_link("SSC-Core","SSC-M-SW3",label="Gg 1/2/3  to Gig 1/0/52",style=link_style)
diagram.add_link("SSC-Core","SSC-R2",label="Gg 2/3/47 to Gig 0/0",style=link_style)
diagram.add_link("SSC-Core","SSC-R1",label="Gg 1/3/47 to Gig 0/0",style=link_style)
diagram.add_link("SSC-Core","SSC-M-SW01",label="Gg 2/2/1  to Gig 1/0/51",style=link_style)
diagram.add_link("SSC-Core","SSC-M-SW01",label="Gg 1/2/1  to Gig 1/0/52",style=link_style)
diagram.add_link("SSC-Core","SSC-M-SW02",label="Gg 1/2/2  to Gig 1/0/52",style=link_style)
diagram.add_link("SSC-Core","SSC-M-SW02",label="Gg 2/2/2  to Gig 1/0/51",style=link_style)
diagram.add_link("SSC-Core","PDC-N9K5-01",label="Ten 1/1/4  to Eth 3/44",style=link_style)
diagram.add_link("SSC-Core","CTY-CSW-001",label="Gg 2/3/27 to Gig 2/0/2",style=link_style)
diagram.add_link("SSC-Core","CTY-CSW-001",label="Gg 1/3/27 to Gig 1/0/2",style=link_style)
diagram.add_link("SSC-Core","SSC-Server-SW",label="Gg 2/3/17 to Gig 1/0/24",style=link_style)
diagram.add_link("SSC-Core","SSC-Server-SW",label="Gg 1/3/17 to Gig 1/0/23",style=link_style)
diagram.add_link("SSC-Core","SDC-N9K5-01",label="Ten 1/1/3  to Eth 3/17",style=link_style)
diagram.add_link("SSC-Core","SSC-FL4-SW12",label="Gg 1/2/11 to Gig 0/1",style=link_style)
diagram.add_link("SSC-Core","SSC-FL4-SW11",label="Gg 1/2/10 to Gig 0/1",style=link_style)
diagram.add_link("SSC-Core","SSC-FL4-SW10",label="Gg 1/2/9  to Gig 0/1",style=link_style)
diagram.add_link("SSC-Core","SSC-FL3-SW1",label="Gg 1/4/5  to Gig 1/0/51",style=link_style)
diagram.add_link("SSC-Core","SSC-FL4-SW6",label="Gg 1/3/43 to Gig 1/0/48",style=link_style)
diagram.add_link("SSC-Core","SSC-FL4-SW6",label="Gg 2/3/43 to Gig 1/0/47",style=link_style)
diagram.add_link("SSC-Core","SSC-FL4-SW7",label="Gg 1/3/44 to Gig 1/0/48",style=link_style)
diagram.add_link("SSC-Core","SSC-FL4-SW7",label="Gg 2/3/44 to Gig 1/0/47",style=link_style)
diagram.add_link("SSC-Core","SSC-nternet-SW1",label="Gg 1/3/28 to Gig 1/0/21",style=link_style)
diagram.add_link("SSC-Core","SSC-FL2-SW2",label="Gg 1/2/5  to Gig 1/0/52",style=link_style)
diagram.add_link("SSC-Core","SSC-FL2-SW2",label="Gg 2/2/5  to Gig 1/0/51",style=link_style)
diagram.add_link("SSC-Core","SSC-nternet-SW1",label="Gg 2/3/21 to Gig 1/0/12",style=link_style)
diagram.add_link("SSC-Core","SSC-FL4-SW4",label="Gg 1/3/41 to Gig 1/0/48",style=link_style)
diagram.add_link("SSC-Core","SSC-FL4-SW4",label="Gg 2/3/41 to Gig 1/0/47",style=link_style)
diagram.add_link("SSC-Core","SSC-FL2-SW3",label="Gg 2/2/6  to Gig 1/0/51",style=link_style)
diagram.add_link("SSC-Core","SSC-FL2-SW3",label="Gg 1/2/6  to Gig 1/0/52",style=link_style)
diagram.add_link("SSC-Core","SSC-FL3-SW2",label="Gg 2/4/4  to Gig 1/0/51",style=link_style)
diagram.add_link("SSC-Core","SSC-FL4-SW5",label="Gg 1/3/42 to Gig 1/0/48",style=link_style)
diagram.add_link("SSC-Core","HO-FL4-SW",label="Gg 2/3/32 to Gig 0/2",style=link_style)
diagram.add_link("SSC-Core","SSC-FL2-SW4",label="Gg 1/2/7  to Gig 1/0/52",style=link_style)
diagram.add_link("SSC-Core","SSC-FL2-SW4",label="Gg 2/2/7  to Gig 1/0/51",style=link_style)
diagram.add_link("SSC-Core","SSC-FL3-SW5",label="Gg 1/4/4  to Gig 0/2",style=link_style)
diagram.add_link("SSC-Core","SSC-FL4-SW2",label="Gg 2/3/39 to Gig 1/0/47",style=link_style)
diagram.add_link("SSC-Core","SSC-FL4-SW2",label="Gg 1/3/39 to Gig 1/0/48",style=link_style)
diagram.add_link("SSC-Core","SSC-FL2-SW5",label="Gg 2/2/8  to Gig 1/0/51",style=link_style)
diagram.add_link("SSC-Core","SSC-FL2-SW5",label="Gg 1/2/8  to Gig 1/0/52",style=link_style)
diagram.add_link("SSC-Core","SSC-FL5-SW2",label="Gg 1/4/6  to Gig 1/0/52",style=link_style)
diagram.add_link("SSC-Core","SSC-FL5-SW2",label="Gg 2/4/6  to Gig 1/0/51",style=link_style)
diagram.add_link("SSC-Core","SSC-FL3-SW4",label="Gg 1/4/2  to Gig 1/0/50",style=link_style)
diagram.add_link("SSC-Core","SSC-FL4-SW3",label="Gg 1/3/40 to Gig 1/0/48",style=link_style)
diagram.add_link("SSC-Core","SSC-FL5-SW1",label="Gg 2/4/7  to Gig 1/0/52",style=link_style)
diagram.add_link("SSC-Core","SSC-FL5-SW1",label="Gg 1/4/7  to Gig 1/0/51",style=link_style)
diagram.add_link("SSC-Core","SSC-FL3-SW7",label="Gg 2/4/5  to Gig 1/0/52",style=link_style)
diagram.add_link("SSC-Core","SSC-FL4-SW1",label="Gg 1/3/38 to Gig 1/0/48",style=link_style)
diagram.add_link("SSC-Core","SSC-FL4-SW1",label="Gg 2/3/38 to Gig 1/0/47",style=link_style)
diagram.add_link("SSC-Core","SSC-FL2-SW8",label="Gg 2/4/3  to Gig 1/0/52",style=link_style)
diagram.add_link("SSC-Core","SSC-FL2-SW8",label="Gg 1/4/3  to Gig 1/0/51",style=link_style)
diagram.add_link("SSC-Core","SSC-FL4-SW8",label="Gg 2/3/26 to Gig 1/0/23",style=link_style)
diagram.add_link("SSC-Core","SSC-FL4-SW8",label="Gg 1/3/22 to Gig 1/0/24",style=link_style)
diagram.add_link("SSC-Core","HO-SW3560X",label="Gg 2/3/24 to Gig 0/22",style=link_style)


diagram.layout(algo="kk")
diagram.dump_file(filename="trungnl"+nowtime+"s.drawio", folder="./Output/")
print(nowtime)
print("Đã export file to ./Output")