# Description: This program will read the key and encrypted pwd generated by GenerateEncryptedKey program. Can be executed multiple time.
from cryptography.fernet import Fernet

# read encrypted pwd and convert into byte
with open('encryptedPWD.txt') as f:
    encpwd = ''.join(f.readlines())
    encpwdbyt = bytes(encpwd, 'utf-8')
f.close()

# read key and convert into byte
with open('refKey.txt') as f:
    refKey = ''.join(f.readlines())
    refKeybyt = bytes(refKey, 'utf-8')
f.close()

# use the key and encrypt pwd
keytouse = Fernet(refKeybyt)
myPass = (keytouse.decrypt(encpwdbyt))
print("my password - ",myPass)
